/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


typedef volatile unsigned int vuint32_t;
#include <stdint.h>

#define RCC_BASE       0x40021000
#define GPIOA_BASE     0x40010800
#define RCC_APB2ENR    (*(volatile uint32_t *)(RCC_BASE   + 0x18))
#define GPIOA_CRH      (*(volatile uint32_t *)(GPIOA_BASE + 0x04))
#define GPIOA_ODR      (*(volatile uint32_t *)(GPIOA_BASE + 0x0C))

#define RCC_IOPAEN     (1U<<2)
#define GPIOA13        (1U<<13)

typedef union {
    uint32_t all_fields;
    struct {
        uint32_t reserved:13;
        uint32_t P_13:1;
    } Pin;
} R_ODR_t;

volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)(GPIOA_BASE + 0x0C);
unsigned char g_variables[3] = { 1 , 2 , 3 } ;
unsigned char const const_variables[3] = {1 , 2 , 3} ;
volatile unsigned char bss_var [3] ;

int main(void)
{
    *((volatile uint32_t *)(RCC_BASE + 0x18)) |= RCC_IOPAEN;
    *((volatile uint32_t *)(GPIOA_BASE + 0x04)) &= 0xFF0FFFFF;
    *((volatile uint32_t *)(GPIOA_BASE + 0x04)) |= 0x00200000;

    while(1)
    {
        R_ODR->Pin.P_13 = 1;
        volatile int i ;
        for ( i = 0; i < 5000; i++);
        R_ODR->Pin.P_13 = 0;
        for ( i = 0; i < 5000; i++);
    }
}
